
services:
  api:
    build: .
    ports:
      - "81:8080"
    volumes:
      - .:/app
    # O comando abaixo sobrescreve o CMD do Dockerfile para habilitar o --reload,
    # ideal para o desenvolvimento.
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]


